import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="http://localhost:3000/">Flowers Wiki!</a>
        </h1>
        <div className={styles.grid}>
          <a href="http://localhost:3000/flowers/dalia" className={styles.card}>
            <h2>Dalia Flower &rarr;</h2>
            <p>Click to know more!</p>
          </a>

          <a href="http://localhost:3000/flowers/lily" className={styles.card}>
            <h2>Lily Flower &rarr;</h2>
            <p>Click to know more!</p>
          </a>

          <a
            href="http://localhost:3000/flowers/rose"
            className={styles.card}
          >
            <h2>Rose flower &rarr;</h2>
            <p>Click to know more!</p>
          </a>

          <a
            href="http://localhost:3000/flowers/tulip"
            className={styles.card}
          >
            <h2>Tulip flower &rarr;</h2>
            <p>
              Click to know more!
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
